bank_app/urls.py
from .import views
from django.urls import path
app_name='bank_app'
urlpatterns = [
     path('',views.home, name="home"),
     path('membership', views.membership, name='membership'),
     path('get-branches/', views.get_branches, name='get_branches'),

]

bank_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
    path('credentials/', include('credentials.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#username: task
#email: sainul@gmail.com
#pwd: 123456

credentials/urls.py
from .import views
from django.urls import path
app_name='credentials'
urlpatterns = [
    path('register',views.register, name="register"),
    path('login', views.login, name='login'),
    path('logout', views.logout,name='logout')

    ]

bank_app/models.py
from django.db import models
from django.shortcuts import redirect
from django.utils.text import slugify  # Import slugify function



# Create your models here.
class District(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    wikipedia = models.CharField(max_length=250)


    class Meta:
        ordering = ('name',)
        verbose_name = 'district'
        verbose_name_plural = 'districts'

    def get_url(self):
        return self.wikipedia
    def __str__(self):
        return '{}'.format(self.name)
class Branch(models.Model):
    name = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.name)

class ApplicationForm(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female')])
    phone_number = models.CharField(max_length=15)
    mail_id = models.EmailField()
    address = models.TextField()

    district = models.ForeignKey('District', on_delete=models.CASCADE)
    branch = models.ForeignKey('Branch', on_delete=models.CASCADE)
    account_type = models.CharField(max_length=20, choices=[('savings', 'Savings Account'), ('current', 'Current Account')])
    materials_provided = models.ManyToManyField('MaterialProvided')

    def __str__(self):
        return '{}'.format(self.name)

class MaterialProvided(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.name)

credentials/models.py
from django.db import models

# Create your models here.

bank_app/forms.py
from django import forms
from .models import District, Branch

from django import forms
from .models import ApplicationForm

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = ApplicationForm
        fields = ['name', 'dob', 'age', 'gender', 'phone_number', 'mail_id', 'address', 'district', 'branch', 'account_type', 'materials_provided']

    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)
        # You can add additional form customization here if needed

        # For example, you can customize the labels, widgets, and other form attributes:
        self.fields['dob'].widget = forms.TextInput(attrs={'type': 'date'})

    # You can also add custom validation logic here if needed

bank_app/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from .models import *
from .forms import ApplicationForm,Branch


# Create your views here.
def home(request):
    return render(request, 'home.html')


def membership(request):
    if request.method == 'POST':
        # If the form has been submitted, process the data
        form = ApplicationForm(request.POST or None)
        if form.is_valid():
            form.save()
            return render(request, 'succesmessage.html')
    else:
        # If the form hasn't been submitted, create a new form instance
        form = ApplicationForm()

    return render(request, 'membership.html',{'form': form})

def get_branches(request):
    district_id = request.GET.get('district')
    branches = Branch.objects.filter(district=district_id).values('id', 'name')

    # Convert QuerySet to dictionary
    branch_data = {branch['id']: branch['name'] for branch in branches}

    return JsonResponse({'branches': branch_data})

credentials/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('bank_app:home')
        else:
            messages.info(request,"invalid credentials")
            return redirect('credentials:login')
    return render(request, "signin.html")
def register(request):
    if request.method == 'POST':
        username=request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username Taken")
                return  redirect('credentials:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"Email Taken")
                return  redirect('credentials:register')
            else:
                user=User.objects.create_user(username=username,password=password,first_name=first_name,last_name=last_name,email=email)
                user.save()
                return redirect('credentials:login')
        else:
            messages.info(request,"Password not matching")
            return redirect('credentials:register')
        return redirect('/')
    return render(request, 'signin.html')

def logout(request):
    auth.logout(request)
    return redirect('credentials:login')

templates/footer.html
{% load static %}
<section class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </section>
  <!-- footer section -->

  <!-- jQery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Finexo </title>


  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">



  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>

<body>

  <div class="hero_area">

    <div class="hero_bg_box">
      <div class="bg_img_box">
        <img src="{% static 'images/hero-bg.png' %}" alt="">
      </div>
    </div>

    <!-- header section strats -->
    {% include 'nav.html' %}
    <!-- end header section -->
    <!-- slider section -->

    {% block content %}
    {% endblock %}

  <!-- end info section -->

  <!-- footer section -->
  </div>
   {% include 'footer.html' %}

  <!-- End Google Map -->
</body>

</html>

templates/membership.html
{% extends 'index.html' %}
{% load static %}
{% block header %}
  <!-- bootstrap core css -->
{% endblock %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>

    $(document).ready(function () {
    // Function to update branch options based on the selected district
    function updateBranches() {
        var selectedDistrict = $('#id_district').val();

        // Make an AJAX request to get branches for the selected district
        $.ajax({
            url: '/get-branches/',  // Replace with your actual URL for fetching branches
            data: {'district': selectedDistrict},
            dataType: 'json',
            success: function (data) {
                // Clear existing options
                $('#id_branch').empty();

                // Add new options based on the received data
                $.each(data.branches, function (key, value) {
                    $('#id_branch').append('<option value="' + key + '">' + value + '</option>');
                });
            }
        });
    }

    // Attach the updateBranches function to the change event of the district field
    $('#id_district').change(updateBranches);

    // Call updateBranches initially to populate branches based on the default district
    updateBranches();
});
</script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/membership.css' %}">
<h1 style="color:white;"><center>Banking Application Form</center></h1>
<div class="container"   >
    <form method="post" style="color:orange;" class="custom-form form-check">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
    </div>
<br>
<br>
{% endblock %}

templates/nav.html
<header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="index.html">
            <span>
              Finexo
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item active">
                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
              </li>
               <li class="nav-item dropdown ">
          <div class="nav-link">
  <button class="nav-link dropdown-toggle" style="color:white;background-color:darkblue;" data-bs-toggle="dropdown" aria-expanded="false">
    Branches
  </button>
  <ul class="dropdown-menu" style="z-index:1">
               {% for district in links %}
<li><a href="{{ district.get_url }}" target="_blank">{{ district.name }}</a></li>
  {% endfor %}

  </ul>
</div>
        </li>
                     {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="">Hello {{ user.username}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credentials:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credentials:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credentials:login' %}">Login</a>
        </li>
        {% endif %}
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>

@import url('https://fonts.googleapis.com/css?family=Montserrat:400,800');

* {
	box-sizing: border-box;
}

body {
	background: #f6f5f7;
	display: flex;
	justify-content: center;
	align-items: center;
	flex-direction: column;
	font-family: 'Montserrat', sans-serif;
	height: 100vh;
	margin: -20px 0 50px;
}

h1 {
	font-weight: bold;
	margin: 0;
}

h2 {
	text-align: center;
}

p {
	font-size: 14px;
	font-weight: 100;
	line-height: 20px;
	letter-spacing: 0.5px;
	margin: 20px 0 30px;
}

span {
	font-size: 12px;
}

a {
	color: #333;
	font-size: 14px;
	text-decoration: none;
	margin: 15px 0;
}

button {
	border-radius: 20px;
	border: 1px solid #FF4B2B;
	background-color: #FF4B2B;
	color: #FFFFFF;
	font-size: 12px;
	font-weight: bold;
	padding: 12px 45px;
	letter-spacing: 1px;
	text-transform: uppercase;
	transition: transform 80ms ease-in;
}

button:active {
	transform: scale(0.95);
}

button:focus {
	outline: none;
}

button.ghost {
	background-color: transparent;
	border-color: #FFFFFF;
}

form {
	background-color: #FFFFFF;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	padding: 0 50px;
	height: 100%;
	text-align: center;
}

input {
	background-color: #eee;
	border: none;
	padding: 12px 15px;
	margin: 8px 0;
	width: 100%;
}

.container {
	background-color: #fff;
	border-radius: 10px;
  	box-shadow: 0 14px 28px rgba(0,0,0,0.25),
			0 10px 10px rgba(0,0,0,0.22);
	position: relative;
	overflow: hidden;
	width: 768px;
	max-width: 100%;
	min-height: 480px;
}

.form-container {
	position: absolute;
	top: 0;
	height: 100%;
	transition: all 0.6s ease-in-out;
}

.sign-in-container {
	left: 0;
	width: 50%;
	z-index: 2;
}

.container.right-panel-active .sign-in-container {
	transform: translateX(100%);
}

.sign-up-container {
	left: 0;
	width: 50%;
	opacity: 0;
	z-index: 1;
}

.container.right-panel-active .sign-up-container {
	transform: translateX(100%);
	opacity: 1;
	z-index: 5;
	animation: show 0.6s;
}

@keyframes show {
	0%, 49.99% {
		opacity: 0;
		z-index: 1;
	}

	50%, 100% {
		opacity: 1;
		z-index: 5;
	}
}

.overlay-container {
	position: absolute;
	top: 0;
	left: 50%;
	width: 50%;
	height: 100%;
	overflow: hidden;
	transition: transform 0.6s ease-in-out;
	z-index: 100;
}

.container.right-panel-active .overlay-container{
	transform: translateX(-100%);
}

.overlay {
	background: #FF416C;
	background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
	background: linear-gradient(to right, #FF4B2B, #FF416C);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: 0 0;
	color: #FFFFFF;
	position: relative;
	left: -100%;
	height: 100%;
	width: 200%;
  	transform: translateX(0);
	transition: transform 0.6s ease-in-out;
}

.container.right-panel-active .overlay {
  	transform: translateX(50%);
}

.overlay-panel {
	position: absolute;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	padding: 0 40px;
	text-align: center;
	top: 0;
	height: 100%;
	width: 50%;
	transform: translateX(0);
	transition: transform 0.6s ease-in-out;
}

.overlay-left {
	transform: translateX(-20%);
}

.container.right-panel-active .overlay-left {
	transform: translateX(0);
}

.overlay-right {
	right: 0;
	transform: translateX(0);
}

.container.right-panel-active .overlay-right {
	transform: translateX(20%);
}

.social-container {
	margin: 20px 0;
}

.social-container a {
	border: 1px solid #DDDDDD;
	border-radius: 50%;
	display: inline-flex;
	justify-content: center;
	align-items: center;
	margin: 0 5px;
	height: 40px;
	width: 40px;
}

footer {
    background-color: #222;
    color: #fff;
    font-size: 14px;
    bottom: 0;
    position: fixed;
    left: 0;
    right: 0;
    text-align: center;
    z-index: 999;
}

footer p {
    margin: 10px 0;
}

footer i {
    color: red;
}

footer a {
    color: #3c97bf;
    text-decoration: none;
}
    </style>

</head>
<body>
<h2>Finexo</h2>
<div class="container" id="container">
	<div class="form-container sign-up-container">
		<form action="register" method="post">
			 {% csrf_token %}
			<h1>Create Account</h1>
			<input type="text" name="username" placeholder="Username" />
            			<input type="text" name="first_name" placeholder="First Name" />
			<input type="text" name="last_name" placeholder="Last Name" />

			<input type="email" name="email" placeholder="Email" />
			<input type="password" name="password" placeholder="Password" />
            			<input type="password" name="password1" placeholder="Confirm Password" />

			<button type="submit">Sign Up</button>
		</form>
	</div>
	<div class="form-container sign-in-container">
		<form action="login" method="post">
             {% csrf_token %}
			<h1>Sign in</h1>
			<div class="social-container">
				<a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
				<a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
				<a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
			</div>
			<span>or use your account</span>
			<input type="text" name="username" placeholder="username" />
			<input type="password" name="password" placeholder="Password" />
			<a href="#">Forgot your password?</a>
			<button type="submit">Sign In</button>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome Back!</h1>
				<p>To keep connected with us please login with your personal info</p>
				<button class="ghost" id="signIn">Sign In</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Hello, Friend!</h1>
				<p>Enter your personal details and start journey with us</p>
				<button type="submit" class="ghost" id="signUp">Sign Up</button>
			</div>
		</div>
	</div>
</div>

<footer>
	<p>
		Created with <i class="fa fa-heart"></i> by
		<a target="_blank" href="https://florin-pop.com">Florin Pop</a>
		- Read how I created this and how you can join the challenge
		<a target="_blank" href="https://www.florin-pop.com/blog/2019/03/double-slider-sign-in-up-form/">here</a>.
	</p>
</footer>
</body>
 <script>
        const signUpButton = document.getElementById('signUp');
const signInButton = document.getElementById('signIn');
const container = document.getElementById('container');

signUpButton.addEventListener('click', () => {
	container.classList.add("right-panel-active");
});

signInButton.addEventListener('click', () => {
	container.classList.remove("right-panel-active");
});
    </script>
</html>

templates/succesmessage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Thanks for being awesome! </h1>
<p>
We have received your message and would like to thank you for writing to us. If your inquiry is urgent, please use the telephone number listed below to talk to one of our staff members.

Otherwise, we will reply by email as soon as possible.

Talk to you soon <a href="{% url 'bank_app:home' %}">Home</a></p>

</body>
</html>